# Generated by Django 6.0.6 on 2026-06-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='occupation',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
