# Generated by Django 6.0.6 on 2026-06-28 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_socialuser_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
